### ISSUE TITLE
Chess pieceName stored incorrectly.

### ISSUE THREAD

**Issue by itsjusttriz** [TheTurkeyDev/Discord-Games#16]
Discord User `HaloSpark334#3272` on your own Discord had pointed out that while trying to move the Queen to an invalid position, it would wrongly mention not being able to move the 'Rook' to that area.

![image](https://user-images.githubusercontent.com/29345907/123877308-dd582400-d934-11eb-933c-bef905d00289.png)

**Comment by CatsClan** [comment]
Hello, friends! 

In chess, I noticed one jamb: when you move as a Queen, there is often a mistake that it is not a queen, but a Rook or Bishop and it is impossible to make a move.

Please tell me if there is any way to fix this error, he really wants to play your chess on his server with friends! 

In general, the bot turned out to be very cool! Thank you for it!

**Comment by itsjusttriz** [comment]
@CatsClan Is the issue just the piece name being wrong, or that you are unable to move your intended piece also?

**Comment by CatsClan** [comment]
Yes, I cant to move piece

**Comment by itsjusttriz** [comment]
User above has failed to respond with more than enough time. It seems this issue will not be fixed, as it is not urgent to the game's mechanics. If the above user continues to endure related issues, they may open another ticket in the Issue Tracker.
